const types = {
  SET_NUMBER_OF_GAMES: "SET_NUMBER_OF_GAMES",
  WHO_STARTS_GAME: "WHO_STARTS_GAME",
  SET_CURRENT_PLAYER: "SET_CURRENT_PLAYER",
  SET_CURRENT_GAME_WINNER: "SET_CURRENT_GAME_WINNER",
  SET_GAMEOVER_FLAG: "SET_GAMEOVER_FLAG",
  START_NEXT_GAME: "START_NEXT_GAME",
  END_TOURNAMENT: "END_TOURNAMENT",
  UNDO_STEP: "UNDO_STEP",
  SET_PLAYER_NAME: "SET_PLAYER_NAME",

  //////////////////////////////////////////////////////////////

  SET_NAME_MODAL_DATA: "SET_NAME_MODAL_DATA",
  PLAYER_NAME_CHANGE: "PLAYER_NAME_CHANGE",
};

export default types;
